export const GET_CALIFICATIONS = "GET_CALIFICATIONS";
export const GET_CALIFICATIONS_SUCCESS = "GET_CALIFICATIONS_SUCCESS";
export const GET_CALIFICATIONS_ERROR = "GET_CALIFICATIONS_ERROR";
export const CLEAR_CALIFICATIONS = "CLEAR_CALIFICATIONS";
export const GET_ASIGNATURES = "GET_ASIGNATURES";
export const GET_ASIGNATURES_SUCCESS = "GET_ASIGNATURES_SUCCESS";
export const GET_ASIGNATURES_ERROR = "GET_ASIGNATURES_ERROR";
